services:
  - type: web
    name: reporte-celular
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server.app:app --bind 0.0.0.0:$PORT --workers 1 --threads 2
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
